title: 工科创 3C 第39组
description: 基于安卓的智能车系统
baseurl: "/kc/2016-12/C39"
url: "http://eelab.sjtu.edu.cn"

# Build settings
markdown: kramdown

theme: minima

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - genPDF.py
  - deploy.sh

# Print
printPDF: false

# CDN
cdn:
  url: http://ohecbiy0g.bkt.clouddn.com/kc3c

# GitHub
github:
  repo: https://github.com/henryly94/kc3c
